    -- -- 严格样式
    -- {
    --     "emileferreira/nvim-strict",
    --     event = "BufReadPost",
    --     config = function ()
    --         local strict = require("strict")
    --         local sopts = {noremap = true,silent = true}
    --         vim.keymap.set('n', '<Leader>flw', strict.remove_trailing_whitespace, sopts)
    --         vim.keymap.set('n', '<Leader>fle', strict.remove_trailing_empty_lines, sopts)
    --         vim.keymap.set('n', '<Leader>flt', strict.convert_spaces_to_tabs, sopts)
    --         vim.keymap.set('n', '<Leader>fls', strict.convert_tabs_to_spaces, sopts)
    --         vim.keymap.set('n', '<Leader>fll', strict.split_overlong_lines, sopts)
    --         strict.setup({
    --             exclude_filetypes = {"markdown","org","norg","tex","html"},
    --             exclude_buftypes = {"help","nofile","terminal","prompt"},
    --             deep_nesting = {
    --                 depth_limit = 5,
    --                 ignored_trailing_characters = ',',
    --                 ignored_leading_characters = '.',
    --             },
    --             trailing_whitespace = {
    --                 highlight = true,
    --             },
    --             overlong_lines = {
    --                 length_limit = 120,
    --             },
    --             space_indentation = {
    --                 highlight = false,
    --             },
    --             todos = {
    --                 highlight = false,
    --             }
    --         })
    --     end
    -- }
    -- -- 启动界面
    -- {
    --     "goolord/alpha-nvim",
    --     event = "VimEnter",
    --     opts = function()
    --     local dashboard = require("alpha.themes.dashboard")
    --         local logo = [[
    --         ██╗      █████╗ ███████╗██╗   ██╗██╗   ██╗██╗███╗   ███╗          Z
    --         ██║     ██╔══██╗╚══███╔╝╚██╗ ██╔╝██║   ██║██║████╗ ████║      Z    
    --         ██║     ███████║  ███╔╝  ╚████╔╝ ██║   ██║██║██╔████╔██║   z       
    --         ██║     ██╔══██║ ███╔╝    ╚██╔╝  ╚██╗ ██╔╝██║██║╚██╔╝██║ z         
    --         ███████╗██║  ██║███████╗   ██║    ╚████╔╝ ██║██║ ╚═╝ ██║
    --         ╚══════╝╚═╝  ╚═╝╚══════╝   ╚═╝     ╚═══╝  ╚═╝╚═╝     ╚═╝
    --         ]]
    --
    --         dashboard.section.header.val = vim.split(logo, "\n")
    --         dashboard.section.buttons.val = {
    --             dashboard.button("f", " " .. " Find file", "<cmd>Telescope find_files <CR>"),
    --             dashboard.button("e", " " .. " New file", "<cmd>ene <BAR> startinsert <CR>"),
    --             dashboard.button("h", " " .. " Recent files", "<cmd>Telescope oldfiles <CR>"),
    --             dashboard.button("g", " " .. " Find word", "<cmd>Telescope live_grep <CR>"),
    --             dashboard.button("r", " " .. " Frecency/MRU","<cmd>Telescope frecency<CR>"),
    --             dashboard.button("p", " " .. " Open last projects","<cmd>Telescope projects<CR>"),
    --             dashboard.button("l", "鈴" .. " Lazy", "<cmd>Lazy<CR>"),
    --             dashboard.button("q", " " .. " Quit", "<cmd>qa<CR>"),
    --         }
    --         for _, button in ipairs(dashboard.section.buttons.val) do
    --             button.opts.hl = "AlphaButtons"
    --             button.opts.hl_shortcut = "AlphaShortcut"
    --         end
    --         dashboard.section.footer.opts.hl = "Type"
    --         dashboard.section.header.opts.hl = "AlphaHeader"
    --         dashboard.section.buttons.opts.hl = "AlphaButtons"
    --         dashboard.opts.layout[1].val = 2
    --         return dashboard
    --     end,
    --     config = function(_, dashboard)
    --         if vim.o.filetype == "lazy" then
    --             vim.cmd.close()
    --             vim.api.nvim_create_autocmd("User", {
    --                 pattern = "AlphaReady",
    --                 callback = function()
    --                     require("lazy").show()
    --                 end,
    --             })
    --         end
    --
    --         require("alpha").setup(dashboard.opts)
    --
    --         vim.api.nvim_create_autocmd("User", {
    --             pattern = "LazyVimStarted",
    --             callback = function()
    --                 local stats = require("lazy").stats()
    --                 local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
    --                 dashboard.section.footer.val = "⚡ Neovim loaded " .. stats.count .. " plugins in " .. ms .. "ms"
    --                 pcall(vim.cmd.AlphaRedraw)
    --             end,
    --         })
    --     end
    -- }
